# Generated by Django 4.2.4 on 2025-02-23 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email', models.EmailField(help_text='Email del usuario que solicita el cambio de contraseña', max_length=254, verbose_name='Email')),
                ('code', models.CharField(help_text='Código alfanumérico de 8 caracteres', max_length=8, verbose_name='Código de verificación')),
                ('is_used', models.BooleanField(default=False, help_text='Indica si el código ya fue utilizado', verbose_name='¿Usado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(help_text='El código expira después de 10 minutos', verbose_name='Fecha de expiración')),
            ],
            options={
                'verbose_name': 'Código de restablecimiento',
                'verbose_name_plural': 'Códigos de restablecimiento',
                'ordering': ['-created_at'],
            },
        ),
    ]
